name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm test
        env:
          REACT_APP_API_URL_LOCAL: ${{https://berto-xavi-202209-w6chwe.herokuapp.com/robots/}}
          JWT_SECRET: af1dbc5648a563e9a5bd97d0eb68f41b
